### ISSUE TITLE
Lilypond 2.20 build fails on macOS 10.15.5

### ISSUE THREAD

**Issue by erlend-aasland** [hahnjo/lilypond-binaries#5]
```
WARNING: Please consider installing optional programs or files:  guile < 1.9.0 (installed: 3.0.3) extractpdfmark texi2html <= 1.82 (installed: 5.0) dblatex

ERROR: Please install required programs:  TeX Gyre fonts OTF (make sure the fc-list utility can see them, e.g. 'sudo apt-get install fonts-texgyre', or use --with-texgyre-dir) guile-config < 1.9.0 (installed: 3.0.3) (guile-devel, guile-dev or libguile-dev package) libguile (libguile-dev, guile-devel or guile-dev package). GUILE-with-rational-bugfix
```

**Comment by hahnjo** [comment]
Expected, this is LilyPond 2.21 with Guile 2 and Python 3 only.

**Comment by erlend-aasland** [comment]
An improvement could be to detect the LilyPond version and exit with an error message for LP < 2.21.

**Comment by erlend-aasland** [comment]
BTW, nice to see that LilyPond has upgraded some of its ancient dependencies :)

**Comment by hahnjo** [comment]
> BTW, nice to see that LilyPond has upgraded some of its ancient dependencies :)

Support for Guile 2 is not yet fledged out and not officially supported. But I couldn't get Guile 1.8 to work with 64 bit MinGW and it has other peculiarities such as shared libraries for `srfi`.

**Comment by erlend-aasland** [comment]
Ok. I still think it's worth it to exit with an error if we're trying to build LilyPond pre 2.21. It should be relatively straight-forward to parse the `VERSION` file in the LilyPond source directory, and assert `MAJOR_VERSION` and `MINOR_VERSION`.

**Comment by hahnjo** [comment]
> Ok. I still think it's worth it to exit with an error if we're trying to build LilyPond pre 2.21. It should be relatively straight-forward to parse the `VERSION` file in the LilyPond source directory, and assert `MAJOR_VERSION` and `MINOR_VERSION`.

I don't agree: Eventually, I'd want the whole scripts to be versioned together with LilyPond. It doesn't make sense to complicate the logic more than necessary.

**Comment by erlend-aasland** [comment]
> > Ok. I still think it's worth it to exit with an error if we're trying to build LilyPond pre 2.21. It should be relatively straight-forward to parse the `VERSION` file in the LilyPond source directory, and assert `MAJOR_VERSION` and `MINOR_VERSION`.
> 
> I don't agree: Eventually, I'd want the whole scripts to be versioned together with LilyPond. It doesn't make sense to complicate the logic more than necessary.

Ok, I'd missed that point. Agree with you.
