### ISSUE TITLE
Lilypond 2.21 build fails on macOS 10.15.5

### ISSUE THREAD

**Issue by erlend-aasland** [hahnjo/lilypond-binaries#6]
```
WARNING: Please consider installing optional programs or files:  extractpdfmark (Using GhostScript >= 9.20 together with extractpdfmark can significantly reduce the size of the final PDF files.) dblatex

ERROR: Please install required programs:  TeX Gyre fonts OTF (make sure the fc-list utility can see them, e.g. 'sudo apt-get install fonts-texgyre', or use --with-texgyre-dir) bison >= 2.4.1 (installed: 2.3)
```

**Comment by hahnjo** [comment]
Yes, these are build-time dependencies (as opposed to run-time dependencies) that are expected to be installed, see also the Readme. Fonts could be worth looking into to make sure the correct versions are used.

**Comment by erlend-aasland** [comment]
> Yes, these are build-time dependencies (as opposed to run-time dependencies) that are expected to be installed, see also the Readme.

Will do

> Fonts could be worth looking into to make sure the correct versions are used.

That would be a welcome improvement.
